# netlify.toml (Final and Correct Version with Environment variable mapping)

# This tells Netlify where your functions live.
[functions]
  directory = "netlify/functions"

# This plugin ensures `npm install` is run inside the functions directory.
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions."*"]
  environment = ["IMGBB_API_KEY", "NOMINATIM_GEOCODE_URL"]