# netlify.toml

# This tells Netlify where your functions live.
[functions]
  directory = "netlify/functions"

# This plugin ensures `npm install` is run inside the functions directory.
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions."*"]
  environment = ["CLOUDINARY_CLOUD_NAME", "CLOUDINARY_API_KEY", "CLOUDINARY_API_SECRET", "NOMINATIM_GEOCODE_URL"]